spring.datasource.url=jdbc:postgresql://localhost:5432/VroomVroom
spring.datasource.username=postgres
spring.datasource.password=Pornoenik69
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.datasource.name=GoPitPlay

spring.jpa.defer-datasource-initialization=true
spring.main.allow-circular-references=true