spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/VroomVroom
        username: postgres
        password: Pornoenik69


spring.jpa.properties.hiberante.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.init.mode=always
spring.jpa.init.platform=postgres
spring.jpa.defer-datasource-initializeration=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.datasource.name=GoPitPlay

spring.jpa.defer-datasource-initialization=true
spring.main.allow-circular-references=true