INSERT INTO DRIVER (first_name, last_name, birthdate, country, number, team_Id, win_change_min, win_change_max) values ( 'Max', 'Verstappen', '1997-09-30', 'Netherlands', '1', '1', '75', '100');
INSERT INTO DRIVER (first_name, last_name, birthdate, country, number, team_Id, win_change_min, win_change_max) values ( 'Sergio', 'Perez', '1990-01-26', 'Mexico', '11', '1', '75', '100');
INSERT INTO DRIVER (first_name, last_name, birthdate, country, number, team_Id, win_change_min, win_change_max) values ( 'George', 'Russel', '1998-02-15', 'United Kingdom', '63', '2', '75', '90');
INSERT INTO DRIVER (first_name, last_name, birthdate, country, number, team_Id, win_change_min, win_change_max) values ( 'Lewis', 'Hamilton', '1985-01-07', 'United Kingdom', '44', '2', '75', '90');
INSERT INTO DRIVER (first_name, last_name, birthdate, country, number, team_Id, win_change_min, win_change_max) values ( 'Charles', 'Leclerc', '1997-10-16', 'Monaco', '16', '3', '75', '90');
INSERT INTO DRIVER (first_name, last_name, birthdate, country, number, team_Id, win_change_min, win_change_max) values ( 'Carlos', 'Sainz', '1994-09-01', 'Spain', '55', '3', '75', '90');
INSERT INTO DRIVER (first_name, last_name, birthdate, country, number, team_Id, win_change_min, win_change_max) values ( 'Oscar', 'Piastri', '2001-04-06', 'Australia', '81', '4', '75', '90');
INSERT INTO DRIVER (first_name, last_name, birthdate, country, number, team_Id, win_change_min, win_change_max) values ( 'Lando', 'Norris', '1999-11-13', 'United Kingdom', '4', '4', '75', '90');
INSERT INTO DRIVER (first_name, last_name, birthdate, country, number, team_Id, win_change_min, win_change_max) values ( 'Lance', 'Stroll', '1998-10-29', 'Canada', '18', '5', '50', '80');
INSERT INTO DRIVER (first_name, last_name, birthdate, country, number, team_Id, win_change_min, win_change_max) values ( 'Fernando', 'Alonso', '1981-07-29', 'Spain', '14', '5', '50', '85');
INSERT INTO DRIVER (first_name, last_name, birthdate, country, number, team_Id, win_change_min, win_change_max) values ( 'Esteban', 'Ocon', '1996-09-17', 'France', '31', '6', '50', '80');
INSERT INTO DRIVER (first_name, last_name, birthdate, country, number, team_Id, win_change_min, win_change_max) values ( 'Pierre', 'Gasly', '1996-02-07', 'France', '10', '6', '50', '80');
INSERT INTO DRIVER (first_name, last_name, birthdate, country, number, team_Id, win_change_min, win_change_max) values ( 'Alexander', 'Albon', '1996-03-23', 'Thailand', '23', '7', '30', '80');
INSERT INTO DRIVER (first_name, last_name, birthdate, country, number, team_Id, win_change_min, win_change_max) values ( 'Logan', 'Sargeant', '2000-12-31', 'United States', '2', '7', '20', '80');
INSERT INTO DRIVER (first_name, last_name, birthdate, country, number, team_Id, win_change_min, win_change_max) values ( 'Daniel', 'Ricciardo', '1989-07-01', 'Australia', '03', '8', '30', '80');
INSERT INTO DRIVER (first_name, last_name, birthdate, country, number, team_Id, win_change_min, win_change_max) values ( 'Yuki', 'Tsunoda', '2000-05-11', 'Japan', '22', '8', '30', '80');
INSERT INTO DRIVER (first_name, last_name, birthdate, country, number, team_Id, win_change_min, win_change_max) values ( 'Valtteri', 'Bottas', '1989-08-28', 'Finland', '77', '9', '30', '80');
INSERT INTO DRIVER (first_name, last_name, birthdate, country, number, team_Id, win_change_min, win_change_max) values ( 'Zhou', 'Guanyu', '1999-05-30', 'China', '24', '9', '30', '80');
INSERT INTO DRIVER (first_name, last_name, birthdate, country, number, team_Id, win_change_min, win_change_max) values ( 'Kevin', 'Magnussen', '1992-10-05', 'Denmark', '20', '10', '30', '80');
INSERT INTO DRIVER (first_name, last_name, birthdate, country, number, team_Id, win_change_min, win_change_max) values ( 'Nico', 'Hulkenberg', '1987-08-19', 'Germany', '27', '10', '30', '80');


INSERT INTO TEAM (name, country) values ('Red Bull Racing', 'Austria' );
INSERT INTO TEAM (name, country) values ('Mercedes', 'Germany' );
INSERT INTO TEAM (name, country) values ('Ferrari', 'Italy' );
INSERT INTO TEAM (name, country) values ('McLaren', 'United Kingdom' );
INSERT INTO TEAM (name, country) values ('Aston Martin', 'United Kingdom' );
INSERT INTO TEAM (name, country) values ('Alpine', 'France' );
INSERT INTO TEAM (name, country) values ('Williams', 'United Kingdom' );
INSERT INTO TEAM (name, country) values ('Torro Rosso', 'Italy' );
INSERT INTO TEAM (name, country) values ('Kick Sauber', 'Switzerland' );
INSERT INTO TEAM (name, country) values ('Haas', 'United States' );


INSERT INTO TRACK (name, location, country, distance) values ('Australian Grand Prix', 'Melbourne', 'Australia', '5.278');
INSERT INTO TRACK (name, location, country, distance) values ('Mexico City Grand Prix', 'Mexico City', 'Mexico', '4.360');
INSERT INTO TRACK (name, location, country, distance) values ('Emilia Romagna Grand Prix', 'Imola', 'Italy', '4.909');
INSERT INTO TRACK (name, location, country, distance) values ('Brazilian Grand Prix', 'São Paulo', 'Brazil', '4.309');
INSERT INTO TRACK (name, location, country, distance) values ('Italian Grand Prix', 'Monza', 'Italy', '5.793');
INSERT INTO TRACK (name, location, country, distance) values ('Bahrain Grand Prix', 'Sakhir', 'Bahrain', '5.412');
INSERT INTO TRACK (name, location, country, distance) values ('Azerbaijan Grand Prix', 'Baku', 'Azerbaijan', '6.003');
INSERT INTO TRACK (name, location, country, distance) values ('Spanish Grand Prix', 'Barcelona', 'Spain', '4.657');
INSERT INTO TRACK (name, location, country, distance) values ('Monaco Grand Prix', 'Monte Carlo', 'Monaco', '3.337');
INSERT INTO TRACK (name, location, country, distance) values ('Belgian Grand Prix', 'Spa', 'Belgium', '7.004');
INSERT INTO TRACK (name, location, country, distance) values ('Canadian Grand Prix', 'Montreal', 'Canada', '4.361');
INSERT INTO TRACK (name, location, country, distance) values ('United States Grand Prix', 'Austin', 'United States', '5.513');
INSERT INTO TRACK (name, location, country, distance) values ('Dutch Grand Prix', 'Zandvoort', 'Netherlands', '4.259');
INSERT INTO TRACK (name, location, country, distance) values ('Hungarian Grand Prix', 'Mogyoród', 'Hungary', '4.381');
INSERT INTO TRACK (name, location, country, distance) values ('Saudi Arabian Grand Prix', 'Jeddah', 'Saudi Arabia', '6.174');
INSERT INTO TRACK (name, location, country, distance) values ('Las Vegas Grand Prix', 'Las Vegas', 'United States', '6.201');
INSERT INTO TRACK (name, location, country, distance) values ('Qatar Grand Prix', 'Lusail', 'Qatar', '5.419');
INSERT INTO TRACK (name, location, country, distance) values ('Singapore Grand Prix', 'Marina Bay', 'Singapore', '4.940');
INSERT INTO TRACK (name, location, country, distance) values ('Miami Grand Prix', 'Miami', 'United States', '5.412');
INSERT INTO TRACK (name, location, country, distance) values ('Austrian Grand Prix', 'Spielberg', 'Austria', '4.318');
INSERT INTO TRACK (name, location, country, distance) values ('Chinese Grand Prix', 'Shanghai', 'China', '5.451');
INSERT INTO TRACK (name, location, country, distance) values ('British Grand Prix', 'Silverstone', 'United Kingdom', '5.891');
INSERT INTO TRACK (name, location, country, distance) values ('Japanese Grand Prix', 'Suzuka', 'Japan', '5.807');
INSERT INTO TRACK (name, location, country, distance) values ('Abu Dhabi Grand Prix', 'Abu Dhabi', 'UAE', '5.281');
