DROP TABLE IF EXISTS TBL_DRIVER;
DROP TABLE IF EXISTS TBL_TEAM;
DROP TABLE IF EXISTS TBL_TRACK;
DROP TABLE IF EXISTS TBL_CALENDER;

CREATE TABLE TBL_DRIVER
(
    id   INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    team VARCHAR(250) NOT NULL
);

CREATE TABLE TBL_TEAM
(
    id   INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250) NOT NULL
);

CREATE TABLE TBL_TRACK
(
    id   INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250) NOT NULL
);